Repository Interesting-study/design-pattern-to-kotlin, pull requests merged in 2023-07, with the labels that each got.

#10 feat(Factory-Method): 팩토리 메소드 패턴 관련 예제
  zeri/gof/build.gradle
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/Circle.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/README.md
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/Shape.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/ShapeColor.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/ShapeFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/ShapeType.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/Square.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/Triangle.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/singleton/CheckSingletonInSpring.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/singleton/onlykotlin/CompanionObjectSingletonUser.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/singleton/onlykotlin/LazyInitializationSingletonUser.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/singleton/onlykotlin/ObjectDeclarationSingletonUser.kt
  zeri/gof/src/test/kotlin/com/gof/pattern/factorymethod/example/ShapeFactoryTest.kt
  zeri/gof/src/test/kotlin/com/gof/pattern/singleton/onlykotlin/KotlinSingletonTest.kt
Labels: 정은경, 팩토리 메서드

#12 feat(Abstract Factory): 추상 팩토리 메소드 패턴
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/Anchor.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/ShipPartsFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/Wheel.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/WhiteAnchorPro.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/WhiteShipFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/WhiteShipPartsFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/WhiteWheelPro.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/before/WhiteAnchor.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/before/WhiteShipFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/before/WhiteWheel.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/javatokotlin/after/Ship.kt
  zeri/gof/src/test/kotlin/com/gof/pattern/abstractfactory/after/WhiteShipFactoryTest.kt
Labels: 정은경

#13 feat(abstract-factory): 추상 팩토리 메서드 추가
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/Anchor.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/ShipInventory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/ShipPartsFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/Wheel.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/WhiteAnchorPro.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/WhitePartsProFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/WhiteShipFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/WhiteShipPartsFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/WhiteWheelPro.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/before/WhiteAnchor.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/before/WhiteShipFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/before/WhiteWheel.kt
  ria/gof/src/main/kotlin/com/gof/pattern/example/OrderFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/example/OrderType.kt
  ria/gof/src/main/kotlin/com/gof/pattern/factory/Ship.kt
  ria/gof/src/test/kotlin/com/gof/pattern/abstractFactory/after/ShipInventoryTest.kt
  ria/gof/src/test/kotlin/com/gof/pattern/example/OrderClientKtTest.kt
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/Anchor.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/ShipInventory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/ShipPartsFactory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/Wheel.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/WhiteAnchorPro.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/WhitePartsProFactory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/WhiteShipFactory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/WhiteShipPartsFactory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/WhiteWheelPro.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/before/WhiteAnchor.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/before/WhiteShipFactory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/before/WhiteWheel.java
  ria/java/gof/src/main/java/com/gof/pattern/factoryMethod/after/Ship.java
  ria/java/gof/src/test/java/com/gof/pattern/abstractFactory/after/ShipInventoryTest.java
Labels: 김도희

#18 feat(): 추상 팩토리 메소드 & 팩토리 메소드 패턴
  zeri/gof/build.gradle
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/Anchor.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/ShipPartsFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/Wheel.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/WhiteAnchorPro.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/WhiteShipFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/WhiteShipPartsFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/after/WhiteWheelPro.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/before/WhiteAnchor.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/before/WhiteShipFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/before/WhiteWheel.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/example/Apple.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/example/Banana.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/example/Fruit.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/example/FruitFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/abstractfactory/example/FruitType.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/Circle.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/README.md
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/Shape.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/ShapeColor.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/ShapeFactory.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/ShapeType.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/Square.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/example/Triangle.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/factorymethod/javatokotlin/after/Ship.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/singleton/CheckSingletonInSpring.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/singleton/onlykotlin/CompanionObjectSingletonUser.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/singleton/onlykotlin/LazyInitializationSingletonUser.kt
  zeri/gof/src/main/kotlin/com/gof/pattern/singleton/onlykotlin/ObjectDeclarationSingletonUser.kt
  zeri/gof/src/test/kotlin/com/gof/pattern/abstractfactory/after/WhiteShipFactoryTest.kt
  zeri/gof/src/test/kotlin/com/gof/pattern/abstractfactory/example/FruitFactoryTest.kt
  zeri/gof/src/test/kotlin/com/gof/pattern/factorymethod/example/ShapeFactoryTest.kt
  zeri/gof/src/test/kotlin/com/gof/pattern/singleton/onlykotlin/KotlinSingletonTest.kt
Labels: main 머지

#19 feat: 팩토리 메서드 패턴 & 추상 팩토리 메서드 패턴
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/Anchor.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/ShipInventory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/ShipPartsFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/Wheel.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/WhiteAnchorPro.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/WhitePartsProFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/WhiteShipFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/WhiteShipPartsFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/after/WhiteWheelPro.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/before/WhiteAnchor.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/before/WhiteShipFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/before/WhiteWheel.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/example/BlackTea.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/example/GreenTea.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/example/Tea.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/example/TeaFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/abstractFactory/example/TeaType.kt
  ria/gof/src/main/kotlin/com/gof/pattern/example/OrderFactory.kt
  ria/gof/src/main/kotlin/com/gof/pattern/example/OrderType.kt
  ria/gof/src/main/kotlin/com/gof/pattern/factory/Ship.kt
  ria/gof/src/test/kotlin/com/gof/pattern/abstractFactory/after/ShipInventoryTest.kt
  ria/gof/src/test/kotlin/com/gof/pattern/abstractFactory/example/TeaFactoryTest.kt
  ria/gof/src/test/kotlin/com/gof/pattern/example/OrderClientKtTest.kt
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/Anchor.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/ShipInventory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/ShipPartsFactory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/Wheel.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/WhiteAnchorPro.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/WhitePartsProFactory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/WhiteShipFactory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/WhiteShipPartsFactory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/after/WhiteWheelPro.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/before/WhiteAnchor.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/before/WhiteShipFactory.java
  ria/java/gof/src/main/java/com/gof/pattern/abstractFactory/before/WhiteWheel.java
  ria/java/gof/src/main/java/com/gof/pattern/factoryMethod/after/Ship.java
  ria/java/gof/src/test/java/com/gof/pattern/abstractFactory/after/ShipInventoryTest.java
Labels: main 머지
